/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Island.glb -o components/three/test.tsx 
*/

import { useGLTF } from "@react-three/drei";
import { JSX, forwardRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { LaptopModel } from "./LaptopModel";
import Slogan from "./Slogan";
// import TextModel from "./TextModel";

type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Environment_PalmTree_2: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder002_1_1: THREE.Mesh;
    Cylinder003_1: THREE.Mesh;
    Cylinder003_1_1: THREE.Mesh;
    Cylinder003_1_2: THREE.Mesh;
    Cylinder003_1_3: THREE.Mesh;
    GeoSphere011: THREE.Mesh;
    GeoSphere009: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    GeoSphere010: THREE.Mesh;
    GeoSphere012: THREE.Mesh;
    GeoSphere013: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    GeoSphere015: THREE.Mesh;
    GeoSphere016: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    GeoSphere017: THREE.Mesh;
    GeoSphere018: THREE.Mesh;
    GeoSphere019: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    GeoSphere020: THREE.Mesh;
    touchbar: THREE.Mesh;
    Cube: THREE.Mesh;
  };
  materials: {
    aluminium: THREE.MeshStandardMaterial;
    ["matte.001"]: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    Atlas: THREE.MeshStandardMaterial;
    ["02___Default"]: THREE.MeshStandardMaterial;
    ["04___Default"]: THREE.MeshStandardMaterial;
    ["01___Default"]: THREE.MeshStandardMaterial;
    ["07___Default"]: THREE.MeshStandardMaterial;
    ["08___Default"]: THREE.MeshStandardMaterial;
    ["09___Default"]: THREE.MeshStandardMaterial;
    wire_113135006: THREE.MeshStandardMaterial;
    ["03___Default"]: THREE.MeshStandardMaterial;
    touchbar: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

type IslandProps = {
  html?: boolean;
} & JSX.IntrinsicElements["group"];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const Island = forwardRef<IslandProps, any>(
  ({ html, ...props }, laptopRef) => {
    console.log("html", html);
    const { nodes, materials } = useGLTF(
      "/models/new_island.glb"
    ) as unknown as GLTFResult;

    return (
      <group {...props} position={[0, -0.4, 0]} dispose={null}>
        <group>
          <Slogan />
        </group>
        <group position={[-14.717, 15.575, 16.845]}>
          <mesh
            geometry={nodes.Environment_PalmTree_2.geometry}
            material={materials.Atlas}
            position={[31.592, -15.662, -10.608]}
            rotation={[3.081, -0.285, 2.929]}
            scale={420.306}
          />
        </group>
        <group position={[14, 1, 10]}>
          <mesh ref={laptopRef} translateY={0.02} visible={false}>
            <boxGeometry args={[0.5, 0.2, 0.1]} />
            <meshBasicMaterial color="red" transparent opacity={0.5} />
          </mesh>
          <LaptopModel />
        </group>
        <group position={[0, -1.645, 0]} scale={0.649}>
          <mesh
            geometry={nodes.Cylinder002_1.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.Cylinder002_1_1.geometry}
            material={materials["04___Default"]}
          />
        </group>
        <group position={[0, -1.645, 0]} scale={0.649}>
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["01___Default"]}
          />
          <mesh
            geometry={nodes.Cylinder003_1_1.geometry}
            material={materials["07___Default"]}
          />
          <mesh
            geometry={nodes.Cylinder003_1_2.geometry}
            material={materials["08___Default"]}
          />
          <mesh
            geometry={nodes.Cylinder003_1_3.geometry}
            material={materials["09___Default"]}
          />
        </group>
        <mesh
          geometry={nodes.GeoSphere011.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere009.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials["03___Default"]}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere010.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere012.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere013.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials["03___Default"]}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere015.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere016.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={materials["03___Default"]}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere017.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere018.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere019.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={materials["03___Default"]}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.GeoSphere020.geometry}
          material={materials.wire_113135006}
          position={[0, -0.098, 0]}
          scale={0.649}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[0, -2.382, 0]}
        />
      </group>
    );
  }
);

Island.displayName = "Island";

useGLTF.preload("/models/new_island.glb");
