/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ship.glb -o components/three/Ship.tsx 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BackSail_1: THREE.Mesh;
    BackSail_2: THREE.Mesh;
    BigShip_1: THREE.Mesh;
    BigShip_2: THREE.Mesh;
    BigShip_3: THREE.Mesh;
    BigShip_4: THREE.Mesh;
    BigShip_5: THREE.Mesh;
    Front_Sail_1: THREE.Mesh;
    Front_Sail_2: THREE.Mesh;
    MidleSail_1: THREE.Mesh;
    MidleSail_2: THREE.Mesh;
    Rudder: THREE.Mesh;
    Node: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Fabric: THREE.MeshStandardMaterial;
    LightWood: THREE.MeshStandardMaterial;
    DarkWood: THREE.MeshStandardMaterial;
    DarkRed: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function ShipModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ship.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 7.022, 0]}
        rotation={[-0.121, 0.016, -0.128]}
        scale={22.523}
      >
        <group
          position={[0, 2.453, -1.048]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.BackSail_1.geometry}
            material={materials.Wood}
          />
          <mesh
            geometry={nodes.BackSail_2.geometry}
            material={materials.Fabric}
          />
        </group>
        <group
          position={[-0.002, -0.071, -0.048]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh geometry={nodes.BigShip_1.geometry} material={materials.Wood} />
          <mesh
            geometry={nodes.BigShip_2.geometry}
            material={materials.Fabric}
          />
          <mesh
            geometry={nodes.BigShip_3.geometry}
            material={materials.LightWood}
          />
          <mesh
            geometry={nodes.BigShip_4.geometry}
            material={materials.DarkWood}
          />
          <mesh
            geometry={nodes.BigShip_5.geometry}
            material={materials.DarkRed}
          />
        </group>
        <group
          position={[0, 2.05, 1.134]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Front_Sail_1.geometry}
            material={materials.Wood}
          />
          <mesh
            geometry={nodes.Front_Sail_2.geometry}
            material={materials.Fabric}
          />
        </group>
        <group
          position={[0, 2.486, 0.051]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.MidleSail_1.geometry}
            material={materials.Wood}
          />
          <mesh
            geometry={nodes.MidleSail_2.geometry}
            material={materials.Fabric}
          />
        </group>
        <mesh
          geometry={nodes.Rudder.geometry}
          material={materials.Wood}
          position={[0, 1.273, -1.908]}
          rotation={[-Math.PI, 0, 0]}
          scale={[8.692, 8.692, 1.292]}
        />
      </group>
      <mesh
        geometry={nodes.Node.geometry}
        material={materials.Mat}
        scale={0.235}
      />
    </group>
  );
}

useGLTF.preload("/models/ship.glb");
